# Generated by Django 6.0.2 on 2026-02-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='item',
            name='text',
        ),
        migrations.RemoveField(
            model_name='item',
            name='todolist',
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
